### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-community/prometheus-boshrelease#70]
Hi

when I am upgrading prometheus from version 12.3.3 to 14.0.0, and hitting the grafana dashboard I am getting authentication pop up box multiple times asking for username and password and saying your connection is not private.

**Comment by frodenas** [comment]
Can you please paste your sanitized deployment manifest?

**Comment by cfmagnum** [comment]
[prometheus.txt](https://github.com/cloudfoundry-community/prometheus-boshrelease/files/1005029/prometheus.txt)

**Comment by cfmagnum** [comment]
Above 14.0.0 version The same issue is occuring

**Comment by frodenas** [comment]
The problem is that when you are using the `prometheus.web.external_url` and enabling basic auth for prometheus (via the `nginx.prometheus.auth_password`), the grafana datasource is NOT configuring the prometheus `username` and `password` (you can check this at the Grafana Datasource configuration).

This was fixed at https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/436d131443d363fbb8080ee87dee75af5a7279df. Can you please try upgrading to [v15.1.0](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v15.1.0)?

**Comment by cfmagnum** [comment]
Thanks!
Yes I will try upgrading from 12.3.3 to v15.1.0

**Comment by cfmagnum** [comment]
Hi,
I tried upgrading from 12.3.3 to v15.1.0.
The issue still persists there!

**Comment by frodenas** [comment]
Check the Grafana datasource, there should be a username and password for the prometheus endpoint.

**Comment by cfmagnum** [comment]
I have tried putting the username and passwords, any of it is not working.
Do you want me to paste the manifest for 15.1.0 here?

**Comment by frodenas** [comment]
I'm confused, the user and password should be already there:

![screen shot 2017-05-16 at 22 02 43](https://cloud.githubusercontent.com/assets/405846/26126092/a01052be-3a84-11e7-9129-b27633085f76.png)


When you say that get an authentication pop up box multiple times, is this a browser's basic auth popup?

**Comment by cfmagnum** [comment]
yes, Tried the same username and password that the datasource has, Not working!

**Comment by cfmagnum** [comment]
![capture](https://cloud.githubusercontent.com/assets/13657881/26128897/9d2c32e4-3aab-11e7-8a6a-8dfc1f57637a.PNG)

**Comment by frodenas** [comment]
Have you tried connecting manually to the url specified at the datasource configuration? It should ask you for an user and password.

Also, is there any proxy when connecting to that url?

**Comment by cfmagnum** [comment]
Yes I tried connecting manually, it asked me for username and password and the same username and password worked !

Yes There is a proxy to that url

**Comment by frodenas** [comment]
If there's a proxy, at the grafana datasource settings, try setting `access: direct` at the `http settings`.

**Comment by cfmagnum** [comment]
After doing the same , it does not ask me for username and password but it does not even show anything.
![capture1](https://cloud.githubusercontent.com/assets/13657881/26129705/f1892182-3aae-11e7-8b52-e8d1ec627720.PNG)

**Comment by frodenas** [comment]
Does it happen with all dashboards? if yes, it should be looking for a datasource with name `prometheus`, please check if that's the name of the datasource.

**Comment by frodenas** [comment]
I forgot to comment that [v16.1.0](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v16.1.0) allows you to specify proxy settings. If you set those properties, grafana will use those proxy settings to connect to prometheus.

```
properties:
  env:
    http_proxy:
    https_proxy:
    no_proxy:
```

**Comment by cfmagnum** [comment]
Hello Frodenas,
Now we are not using any proxy.I am attaching prometheus 17.0.0 manifest.I am having one doubt in following section 
    **    security:
      admin_password: REDACTED
      admin_user: admin
      secret_key: REDACTED
    server:
      root_url: http://REDACTED:9093
    session:
      provider: postgres
      provider_config: user=grafanaadmin password=REDACTED host=REDACTED.1.48 dbname=grafanadb
        port=5432 sslmode=disable
  nginx:
    alertmanager:
      auth_password: REDACTED
      auth_username: admin
    prometheus:
      auth_password: REDACTED
      auth_username: admin**

Do we need to add grafana username and password in nginx section .
[prometheus-17.txt](https://github.com/cloudfoundry-community/prometheus-boshrelease/files/1040538/prometheus-17.txt)

**Comment by frodenas** [comment]
No, if you're already securing grafana via user and password you don't need to secure it again via ngnix.

**Comment by cfmagnum** [comment]
I am still facing the same authentication problem.Is there any configuration change I am missing to do.

**Comment by frodenas** [comment]
@cfmagnum There're several things you should update in your manifest:

* The `grafana.promethus.dashboard_files` property should point to `/var/vcap/jobs/...` not `/var/vcap/packages`
* The `grafana.server.root_url` should point to the `nginx` vip and port **3000**
* The `prometheus.server.root_url` should point to the `nginx` vip and port **9090**
* Double check the `prometheus.scrape_configs` ip's. If prometheus is unable to scrape metrics from the exporters, you'll get the **Templating init failed** error message. Go to the prometheus console (vip:9090) and check the `Status -> Targets`.

**Comment by xanderrman** [comment]
@cfmagnum hey, just checking in to see if you've looked more into this :)

**Comment by frodenas** [comment]
@cfmagnum One thing that might happen is that you have changed the grafana admin password. We discovered today that grafana does NOT update the password, and the update datasource config script was failing silently. I don't know if that's you case (you changed the admin password), but if that's the case, this will explain why it was failing. A fix is in the works now.

/cc @geofffranks

**Comment by frodenas** [comment]
This should have been fixed at [v17.4.2](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v17.4.2).
